### ISSUE TITLE
Make IdentityServer4TestServerFactory.GetWebHostBuilder() public (or protected)

### ISSUE THREAD

**Issue by damianh** [devdigital/IdentityServer4TestServer#17]
Nice lib!

Could you consider making IdentityServer4TestServerFactory.GetWebHostBuilder() public or protected? I like the fluent config interface you have here I'd like to use it to build a test server that I can bind to a real listener instead of aspnet core's TestServer (the scenario is a 'DevServer' the runs multiple listeners - IdSrv and my app, amongst others).

https://github.com/devdigital/IdentityServer4TestServer/blob/ec48dab6c897321a27a6ba01fe2ea79a42849774/Source/IdentityServer4TestServer/Factories/IdentityServer4TestServerFactory.cs#L286

**Comment by devdigital** [comment]
Hi, thanks for the feedback. The method has been made protected if you update to the latest NuGet package.
